#!/bin/bash

export DB=${2:-/home/progmatic99/tmp/cachedb/}
export VOLUMES=${1:-localhost:5001}
export TYPE=master

chmod 777 $DB

uwsgi --http :${PORT:-5000} --wsgi-file src/server.py --callable master --master --processes 2
